### ISSUE TITLE
Can't choose resolution in family shared games

### ISSUE THREAD

**Issue by Manu99it** [ChristopherKlay/StadiaEnhanced#105]
As per title, images attached for reference:
Now:
![image](https://user-images.githubusercontent.com/19348772/110814965-40d91b80-828a-11eb-81c3-139ef5fd8f33.png)

How should be (own game):
![image](https://user-images.githubusercontent.com/19348772/110815128-75e56e00-828a-11eb-878e-b66e7eff53a6.png)

**Comment by ChristopherKlay** [comment]
Will be fixed with the next update (:

Thanks for reporting!
