### ISSUE TITLE
Store type filter

### ISSUE THREAD

**Issue by superm1991** [ChristopherKlay/StadiaEnhanced#106]
Hi,

I noticed "Assassin's Creed Origins - Season Pass" which has "17:9" in its jslog (instead of the usual 17:1, 17:2, 17:3).
It looks like the filter didn't account for such a value?

Anyway... the item appears even with "Game" filter ON.

**Comment by ChristopherKlay** [comment]
Honestly this is the first time i even saw a shop item marked as "Add-on-Bundle".
I'm going to fix this and include it under "Add-ons" in the next patch.

Thanks for reporting (:
