### ISSUE TITLE
Suddenly unable to select codec or resolution

### ISSUE THREAD

**Issue by pean74** [ChristopherKlay/StadiaEnhanced#107]
I've earlier been ablte to chose vp9 and 1440p or 2160p  but as of today that is not possible. I've tried two different Windows 10 machinges and the result is the same.

**Comment by ChristopherKlay** [comment]
Just tested on multiple devices; 1440p/2160p worked on both.

Can you re-select "Up to 4K" under Stadias settings and try again?

**Comment by pean74** [comment]
Seems I can't do that anymore. It says that my device doesn't support that resolution. My monitor doesn't but it worked earlier anyway.

**Comment by ChristopherKlay** [comment]
When you try and select it, is it greyed out or does it just revert to 1080p after selecting it?

Also, if you open up the console (F12) are there any errors being reported?

**Comment by pean74** [comment]
It justs reverts back to 1080p. I can see no errors in the console.

**Comment by ChristopherKlay** [comment]
The reverting is (sadly) normal, but it's just a visual bug.

Since Stadia doesn't detect you having a 4K screen and the 4K option is disabled by default (Enhanced enables it), it reverts back to 1080p - but 4K is still your selected option after selecting it once.

Can you set the option to 1440p in the Enhanced menu, start a game, let it load up to the titlescreen and make a screenshot of the stream monitor (shift+tab > stream monitor)?

**Comment by pean74** [comment]
![printscreen](https://user-images.githubusercontent.com/73824417/111640085-222fd300-87fc-11eb-8af1-12ea624b6888.jpg)

**Comment by ChristopherKlay** [comment]
Okay, so for some reason you are defaulting to (Hardware) H264 - which is limited to 1080p.

With a game open, can you throw this into the console and copy me the output?

``localStorage.getItem("video_codec_implementation_by_codec_key");``

It will show the detected codec - which *should* be VP9, if you select 1440p.

**Comment by pean74** [comment]
I get this output; "{"vp9":"ExternalDecoder"}"

So at least it seems to be the correct codec

**Comment by ChristopherKlay** [comment]
It looks like VP9 is selected correctly, but the stream defaults to H264 - which usually only happens the other way around on errors and such.

Are you trying to run 1440p/2160p via a GPU that supports VP9, or via software decoding and your CPU?

**Comment by pean74** [comment]
I'm trying to do it with software decoding. It has been working earlier.

**Comment by ChristopherKlay** [comment]
I'm definitely looking into it, but what you could try is disabling hardware acceleration - if it's active.

The option is in your browsers menu under settings > advanced > system, labeled as "Use hardware acceleration when available”.

**Comment by pean74** [comment]
That changes the codec to vp9 but no matter settings I have. I only get 720p.

**Comment by ChristopherKlay** [comment]
Okay that is.. very weird.

Being limited to 720p once you drop out of hardware support (H264) should only happen if Stadia detects your CPU can't handle more than 720p via software decoding.

If you open a 4K video ([like this](https://www.youtube.com/watch?v=LXb3EKWsInQ)) in YouTube and rightclick the video to open the statistics overlay, does the video actually play fine at 4K via VP9 and without buffering/frame drops?

**Comment by pean74** [comment]
It plays fine at 1440p with no buffering and just a few frame drops.

**Comment by ChristopherKlay** [comment]
Honestly; At this point it's getting tough to guess what the error could be, seeing that it looks like it's limited to a tiny fraction of the userbase, with this being the only report so far.

Have you tried using Stadia via a different browser to see if the issue is based on your current one?

**Comment by pean74** [comment]
I have tried on Edge aswell and have the same problem.

I will try to experiment on my own and thank you for your effort and really nice addon!

**Comment by ChristopherKlay** [comment]
Turns out, this is most likely a issue with changes on Stadias side and you likely just got the update early.

See [here](https://github.com/ChristopherKlay/StadiaEnhanced/issues/109) for more info.
