### ISSUE TITLE
Swedish Translation

### ISSUE THREAD

**Issue by Mafrans** [ChristopherKlay/StadiaEnhanced#11]
LANG: sv

"default":"Standard",
"native":"Inbyggd",
"disabled":"Inaktiverat",
"windowed":"Fönsterläge",
"fullscreen":"Fullskärmsläge",
"searchstore":Sök i butiken",
"onsale":"På Rea",
"prodeals":"Pro Deals",
"allgames":"Alla Spel",
"usermedia":"Skärmdumpar & Filmer",
"gridsize":"Rutnätsstorlek",
"friendslist":"Vänner",
"igoverlay":"Spelöverlägg",
"listoverlay":"Lista & Överlägg",
"filtertoggle":"Växla Filter",
"filterquick":"Snabbfilter",
"invitebase":"Kopiera inbjudningslänk",
"inviteactive":"Kopierat!",
"searchbtnbase":"Sök på",
"avatarpopup":"Nytt avatar-URL (lämna tomt för standard):",
"searchheader":"Spel inklusive",
"sessiontime":"Sessionstid",
"codec":"Kodec",
"trafficsession":"Sessionstrafik",
"trafficcurrent":"Nuvarande trafik",
"trafficaverage":"Genomsnittlig trafik",
"packetloss":"Tappade paket",
"framedrop":"Tappade bilder",
"latency":"Latens",
"jitter":"Jitter Buffer",
"compression":"Kompression",
"streammon":"Strömmonitor"
"resolution":"Upplösning",
"stream": "Ström",
"community": "Gemenskap",
"speedtest": "Hastighetstest",
"quickaccess": "Snabbmeny",
"messages": "Meddelanden",
"prolabel": "Pro-Etikett",
"homegallery": "Användargalleri",
"quickprev": "Förhandsvisning av Meddelande",
"quickrep": "Snabbsvar",
"offlinefriend": "Offlinevänner",
"invisiblefriend": "Osynliga Vänner",
"avatar": "Avatar",
"shortcutshover":"Göm Genvägar Automatiskt",
"shortcutstoggle":"Genvägar",
"streammode": "Streamer-läge",
"interface": "Gränssnitt"

**Comment by ChristopherKlay** [comment]
Just updated the translation file with the missing line; `"resolution": "Resolution",`
Would be lovely if you could translate that, so i can push a hotfix for the streaming monitor (:

**Comment by Mafrans** [comment]
Done

**Comment by ChristopherKlay** [comment]
New lines for v1.6.0 and the new settings menu/options.

    "stream": "Stream",
    "community": "Community",
    "speedtest": "Speedtest",
    "quickaccess": "Quick Access",
    "messages": "Messages",
    "prolabel": "Pro Label",
    "homegallery": "User Gallery",
    "quickprev": "Message Preview",
    "quickrep": "Quick Reply",
    "offlinefriend": "Offline Friends",
    "invisiblefriend": "Invisible Friends",
    "avatar": "Avatar"

**Comment by ChristopherKlay** [comment]
New lines for v1.7.0 and the shortcut integration.
```
"shortcutshover":"Autohide Shortcut Buttons",
"shortcutstoggle":"Shortcut Buttons"
```

**Comment by Mafrans** [comment]
Updated with the new translations.
I assumed "Quick Access" was in the context of a quick menu access, and have therefore translated it to lit. "Quick Menu". Notify me if that's an issue.

**Comment by ChristopherKlay** [comment]
"Quick Access" is used for header of the menu category that holds shortcuts to the speedtest/community page and others.

Thanks for the update (:

**Comment by ChristopherKlay** [comment]
v1.7.0 was slightly rushed due to changes on Googles end, thus i applied the new version and forgot two strings for 1.7.0;
```
"streammode": "Streaming Mode",
"interface": "Interface"
```
These will be added in a later hotfix when available.

Thank you once more (:

**Comment by Mafrans** [comment]
Updated.
Translated "Streaming Mode" to lit. "Streamer-mode"
