### ISSUE TITLE
Time doesn't have a 12-hour format - I don't like using my brain to do math!

### ISSUE THREAD

**Issue by Phase10-5828** [ChristopherKlay/StadiaEnhanced#117]
See title. I want to be able to know the time at a glance without doing mental conversions. The software already knows the time zone to display the 24-hour time correctly,  so a 12-hour option should be available.

**Comment by ChristopherKlay** [comment]
Fear not - no need to use math!

Try clicking on it :p

**Comment by Phase10-5828** [comment]
I'm dumb. :p

Thanks, lol.
