### ISSUE TITLE
Publish your extension to Microsoft Edge Addons website

### ISSUE THREAD

**Issue by nagachaitanyalokam** [ChristopherKlay/StadiaEnhanced#126]
Microsoft Edge is the second most used browser on the web, making the browsing experience more flexible, offering many more services for users and optimized for Windows devices.

Microsoft Edge now provides developers an option to port their existing Chrome extension to Microsoft Edge Addons website with minimal code changes.

You can find all the details about how to port your extension [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension)

If you have any more queries about porting Chrome extension to Microsoft Edge or anything else, you can contact the relevant teams whose links are given [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-extensions-team).

Let me know if this was helpful. I am happy to help you with more details.

**Comment by ChristopherKlay** [comment]
I'm already in a conversation with the team behind the Microsoft Edge Extension service via mail and explained why publishing the extension on the Edge Add-On market currently isn't considered.
