### ISSUE TITLE
The streaming stat window does not show up

### ISSUE THREAD

**Issue by biomeadows** [ChristopherKlay/StadiaEnhanced#135]
For some reason the streaming stat window (stream monitor) does not show up as of today (06/01/2021). I used shift+tab and selected on show stream monitor option but does not work. Also, tried the automatic option, and it did not work. Any suggestions for a quick fix?

![image](https://user-images.githubusercontent.com/43504752/120426840-aedf2d00-c325-11eb-9020-7590f87cbe30.png)

**Comment by ChristopherKlay** [comment]
There appears to be something going wrong when grabbing the stream data - looking into it now.

Thanks for reporting (:
