### ISSUE TITLE
[minor issue] Controller cannot select options to show/hide Stream Monitor or change to Windowed/Fullscreen mode

### ISSUE THREAD

**Issue by keef-khan** [ChristopherKlay/StadiaEnhanced#137]
This isn't a huge deal, but it is a minor annoyance that means you can only activate the options with a mouse. 

Video demonstration: [https://streamable.com/gtvwm6](https://streamable.com/gtvwm6)

**Comment by ChristopherKlay** [comment]
This is sadly a limitation introduced by Stadias support layer for inputs and the device recognition.

Afaik there currently isn't a way around it, without disabling support for other elements.
