### ISSUE TITLE
[Bug] Extended Info stops showing up after (manual) language change

### ISSUE THREAD

**Issue by m-cerveny** [ChristopherKlay/StadiaEnhanced#147]
I changed the language (to Slovak) and the Extended Info section won't show. Doing "Clear Browsing Data" doesn't help. Really strange...

_Originally posted by @m-cerveny in https://github.com/ChristopherKlay/StadiaEnhanced/discussions/146_

**Comment by ChristopherKlay** [comment]
The extended info is currently missing in general due to a bug. A patch will come out in the next 24 hours (:

**Comment by ChristopherKlay** [comment]
Version `1.5.2` fixing this is now live on GitHub and in verification on the store.
Sorry for the delay! (:

**Comment by m-cerveny** [comment]
No worries, Christopher. Excellent job!
