### ISSUE TITLE
Please pull the locale info from the browser not based off geographic location

### ISSUE THREAD

**Issue by vendion** [ChristopherKlay/StadiaEnhanced#155]
I noticed that Stadia+ handles locale differently than what is set in the browser or in the OS. For example my computer and Chrome is set to en-US for the locale, but since I'm currently in Brazil Stadia+ is using pt-BR thus all it's UI elements are in Portugees rather than English. I did see where I can manually override the auto-detected locale but would be nice if I didn't have to to begin with.

![Screenshot_20210813_103710](https://user-images.githubusercontent.com/145018/129365863-4a5d3f36-bd32-43ac-8648-229795c04612.png)
![Screenshot_20210813_103821](https://user-images.githubusercontent.com/145018/129365882-43297988-4373-43e8-b17e-066cdf7e4034.png)

**Comment by ChristopherKlay** [comment]
Both issues you just opened are about Stadia+, but this is the GitHub page for Stadia Enhanced.

Stadia Enhanced isn't featuring a Google login and already selects the user language based on the language of the Stadia page itself - if it's english, the loaded translation will be as well.

You can find the GitHub page for Stadia+ over [here](https://github.com/Mafrans/StadiaPlus) (:

**Comment by vendion** [comment]
> Both issues you just opened are about Stadia+, but this is the GitHub page for Stadia Enhanced.
> 
> Stadia Enhanced isn't featuring a Google login and already selects the user language based on the language of the Stadia page itself - if it's english, the loaded translation will be as well.
> 
> You can find the GitHub page for Stadia+ over [here](https://github.com/Mafrans/StadiaPlus) (:

Apologies, I got the extensions confused and just confirmed that these are none issues for Stadia Enhanced.
