### ISSUE TITLE
[ minor bug ? ] "Recent changes" tooltip is still on v1.4.0

### ISSUE THREAD

**Issue by Lordubuntu94** [ChristopherKlay/StadiaEnhanced#16]
https://imgur.com/3sr5vqu

I'm on SE v1.5.0

I don't know if it's a problem of mine or a bug, but I've already reinstalled the extension several times and i still have this.

**Comment by ChristopherKlay** [comment]
That's certainly weird.

The current popup file for v1.5.0 definitely has the changes listed and they show up fine for me. But for some reason the store version got stuck with the old popup file from v1.4.0. This will be updated in the next version again (:
