### ISSUE TITLE
Stream Monitor Does not load when playing a game - previously worked.

### ISSUE THREAD

**Issue by MikeRotch76** [ChristopherKlay/StadiaEnhanced#166]
The stream monitor overlay worked yesterday for me.  I did not touch my laptop from yesterday to today, no new updates were installed or anything,  Tonight I fired up my laptop, fired up Chrome, went into Stadia and although the hamburger menu for StadiaEnhanced is there in the Stadia main menu, when I load a game, the monitor does not show up.  I have my Stream Monitor set to automatic.  I did not change any other settings.  Also in game, when I hit shift+tab, and I try to manually click on Stream Monitor, nothing happens.

I tried uninstalling the StadiaEnhanced extension, uninstalling Chrome, rebooting my laptop, then reinstalling Chrome and reinstalling StadiaEnhanced.  This did not fix it.

**Comment by ChristopherKlay** [comment]
I just tested some things related to autostarting the monitor and other things and the monitor shows up for me perfectly fine.

Some things might worth checking;

1. Do you get any errors in the console (Ctrl+Shift+I > Console), or is the monitor simply not showing?
2. If you go to the "Application" tab in the same window and then "Local Storage" > "stadia.google.com" on the left, you should find your user profile - mine would be `enhanced_Confirmae#9763` for example. CLicking it shows all your settings for that account, including `monitorPosition` - maybe it's set to be displayed outside of the screen for some reason?

**Comment by MikeRotch76** [comment]
I loaded up Destiny 2 and am in game and grabbeed  the settings under "Local Storage" and my Stadia user profile.

avatar: ""
clockMode: 0
clockOption: 2
codec: 0
desktopHeight: 1200
desktopWidth: 1920
enableShortcuts: 1
enableStadiaStats: 0
favoriteList: ""
filter: 0
gameFilter: ""
gridSize: 0
hideCategories: 0
hideFamilySharing: 0
hideInlinePreview: 0
hideInvisibleUsers: 0
hideLabels: 0
hideMessagePreview: 0
hideOfflineUsers: 0
hideQuickReply: 0
hideUserMedia: 0
monitorAutostart: 1
monitorMode: 0
monitorPosition: "1rem|1rem"
resolution: 0
splitStore: 0
streamMode: 0
updateNotifications: 0

Looking in the console, there are no errors with the StadiaEnhanced label.  But there is an error that says "This document requires 'TrustedHTML' assignment." and when I click on the link it jumps to this:

                enhanced_streamMonitor.innerHTML = X

Here is the section it is in.

setInterval(function() {
        if (document.location.href.indexOf('/player/') == -1) {
            peerConnections = []
            enhanced_lastBytes = 0
            enhanced_lastFrames = 0
            enhanced_sessionActive = false
        } else if (peerConnections.length >= 2) {
            if (!enhanced_sessionActive) {
                enhanced_sessionStart = new Date()
                enhanced_streamMonitor.innerHTML = X
                <section>
                    <div class="grid">
                        <span style="grid-column: 1 / 4;">Loading stream data.</span>
                    </div>
                </section>`

                // Reset monitor stats
                document.getElementById('enhanced_menuMonitorCodecRes').innerHTML = '<div class="Qg73if"><span class="zsXqkb">' + enhanced_lang.codec + '</span><span class="Ce1Y1c qFZbbe">-</span></div>'
                document.getElementById('enhanced_menuMonitorRes').innerHTML = '<div class="Qg73if"><span class="zsXqkb">' + enhanced_lang.resolution + '</span><span class="Ce1Y1c qFZbbe">-</span></div>'
                document.getElementById('enhanced_menuMonitorLatFps').innerHTML = '<div class="Qg73if"><span class="zsXqkb">' + enhanced_lang.latency + ' | FPS</span><span class="Ce1Y1c qFZbbe">- | -</span></div>'
                document.getElementById('enhanced_menuMonitorFDrop').innerHTML = '<div class="Qg73if"><span class="zsXqkb">' + enhanced_lang.framedrop + '</span><span class="Ce1Y1c qFZbbe">-</span></div>'
                document.getElementById('enhanced_menuMonitorDecode').innerHTML = '<div class="Qg73if"><span class="zsXqkb">' + enhanced_lang.decodetime + '</span><span class="Ce1Y1c qFZbbe">-</span></div>'

                enhanced_sessionActive = true

**Comment by ChristopherKlay** [comment]
Found the issue.

A update in Chrome effectively blocks me from loading the data for the stream monitor into the UI elements for it, because the content isn't "trusted".

I'll see what i can do (:

**Comment by ChristopherKlay** [comment]
**Update:**

`1.16.6` just went live on GitHub and should be live on the Chrome Store soon as well, including a fix for this issue.

Part of the extension is injected into the Stadia website to get access to the stream data and then creates the HTML used for the streaming monitor on the fly - which resulted in these issue, using Chrome. I changed it so it creates a locally stored object containing the stream data and the main script handles the data / updating the monitor - which has some positive side effects, like the translation being directly accessible as well.

Once you are on `1.16.6`, please report back if you still encounter the issue (:

**Comment by MikeRotch76** [comment]
Grabbed 1.16.6 and it's working again.  Thanks!
