### ISSUE TITLE
input lag and framerate is really poor.

### ISSUE THREAD

**Issue by Toiletcleanner69** [ChristopherKlay/StadiaEnhanced#167]
![image](https://user-images.githubusercontent.com/72539877/134742606-409c27d7-d3f9-4275-938a-dbcfe7995d67.png)
![image](https://user-images.githubusercontent.com/72539877/134742612-d1a37e86-f806-40f3-8792-00c26c8ea379.png)

Not sure why the performance is the way it is and i I have good internet, wifi. 100mbs. I uploaded a few images showing my stream settings. I tried all of the different resolutions and encoders this plugins adds but the result is the same. The input lag and framerate is stopping me from playing.

**Comment by Toiletcleanner69** [comment]
I turned on hardware acceleration in my browser settings and the input lag feels better but it feels like my game is freezing every time i turn a corner...

here is what it looks like with hardware acceleration turned on.

![image](https://user-images.githubusercontent.com/72539877/134744310-6b122f8c-a4b3-4947-8fd5-c99eed13099f.png)

**Comment by ChristopherKlay** [comment]
The first two screens definitely show that you had issues with your decoding time and dropping frames because of it - likely due to the high resolution on software decoding and the performance of your CPU.

With hardware decoding enabled, the stats look perfectly fine.

What input devices are you using? Does this happen with all games, or could it be due to this specific one being locked to 30fps?

**Comment by Toiletcleanner69** [comment]
> What input devices are you using? Does this happen with all games, or could it be due to this specific one being locked to 30fps?
My lenovo y520 laptop. Only Assassins creed odyssey. I played destiny 2, RDR2 and hitman. and I never had the same issue with those games

**Comment by ChristopherKlay** [comment]
Could the difference be teh supported framerate?

Both Destiny 2 and RDR2 support 60fps modes, while AC Odyssey is capped at 30fps at any resolution.

**Comment by Toiletcleanner69** [comment]
could be
