### ISSUE TITLE
Integrate tell-tale lights to warn the player about issue mid-game

### ISSUE THREAD

**Issue by Kreyren** [ChristopherKlay/StadiaEnhanced#169]
![image](https://user-images.githubusercontent.com/11302521/135311757-94127e15-fd2b-4424-9b4b-c4572f537760.png)

Lot of competetive games have ""tell-tale lights"" which are flashing on the screen in case there is an issue that influences the player's gameplay (e.g. latency beyond an expected threshold) for them to make decision to reduce the consequences of such issue e.g. retreating under turret in MOBA games instead of proceeding with an attack.

Example: https://www.youtube.com/watch?v=UzsNlKiSNVE?t=1 (notice the red blinking speedometer icon top right indicating high latency)

Proposing such integration in StadiaEnhanced with time logging to be used as a feedback to Google/ISP.

### Motivation

Too many ruined World Records in TheCrew 2 on Stadia.

### Theoretical integration

on-demand infinite loop that checks:
- Latency
- Compression time
- Packet Loss
- Lost connection

every X amount of miliseconds (every 250ms by default seems to be optimal in terms of processing resources) and shows the tell-tale light if it's beyond a set value.

---

CC @ChristopherKlay

**Comment by ChristopherKlay** [comment]
Something similar is actually already part of the extension.

If you open up the stream monitor during a game and doubleclick it (with the Stadia menu open), it switches to the compact view - which features a connection symbol that changes colors based on latency, frame drops, decoding time and other factors.

> Proposing such integration in StadiaEnhanced with time logging to be used as a feedback to Google/ISP.

Maybe a option to save a performance log of the last session, that includes logs with date/time and whatever caused the performance issue?
