### ISSUE TITLE
Mafia III bug

### ISSUE THREAD

**Issue by ike75** [ChristopherKlay/StadiaEnhanced#178]
I have a bug in Mafia III hen appear for the first time the mon talking about the dad.

All this video repeat and repeat, and when I close the game and I launch it again it freezes in the loading screen.

**Comment by ChristopherKlay** [comment]
For game related bugs, please ask the community over on [Reddit](https://www.reddit.com/r/Stadia/).
This GitHub is only for the Stadia Enhanced extension.
