### ISSUE TITLE
Monitor button disappears

### ISSUE THREAD

**Issue by derekagraham78** [ChristopherKlay/StadiaEnhanced#18]
For some reason when I want to see my FPS or resolution etc the button is missing from the menu

**Comment by ChristopherKlay** [comment]
I'm currently not running into this issue and my monitor shows up after the game loaded and the initial start-up check, but i had similar issues in the past where the monitor sometimes doesn't show up when starting a game.

Is the monitor always missing for you?

**Comment by Lordubuntu94** [comment]
Can confirm, sometimes it's missing for me too, usually when i start a game for the 1st time after entering stadia. A refresh usually fix this btw

**Comment by ChristopherKlay** [comment]
I'll look into it. (:

**Comment by derekagraham78** [comment]
it all depends on random circumstances, sometimes it shows up sometimes not, mainly on new games, but ive seen it on old games too

**Comment by ChristopherKlay** [comment]
New update `v1.5.5` with a potential fix is on GitHub now and send into certification for the Chrome Store.
