### ISSUE TITLE
[Feature Request] Add a speedtest tab

### ISSUE THREAD

**Issue by Lordubuntu94** [ChristopherKlay/StadiaEnhanced#19]
I don't know if it is possible, but It would be cool to have a new tab that can show the results on both speed test and ping test from google cloud services.

Specifically i'm referring to something like :
https://projectstream.google.com/speedtest 
https://pingtestlive.com/google-cloud-ping

**Comment by ChristopherKlay** [comment]
It would be possible to do both tests in the background and then showcase the results, but i would like to avoid such actions without the user actively starting them.

I will however at some point create a new page here on GitHub that explains/helps with connection/play issues and will mention those (:
