### ISSUE TITLE
Filter and Monitor tabs dissapear on Stadia Enhanced

### ISSUE THREAD

**Issue by hoangnghia0710** [ChristopherKlay/StadiaEnhanced#192]
I don't know why the filter and monitor tab disappear in my stadia enhanced.
![stadia](https://user-images.githubusercontent.com/93945844/140808108-0efd7a0f-eed4-4c3e-8bfb-307d001bbcf5.jpg)

**Comment by jfidelack** [comment]
Hi, this also happens to me recently.  Running Chrome OS.  Happy to provide diagnostic information.

**Comment by ChristopherKlay** [comment]
Thanks for letting me know! (:

When optimizing the function to insert elements into the Stadia UI, i sadly made a mistake and assumed classes are only letters (a-z & A-Z) and spaces (for use in `getElementsByClassName()`), completely ignoring that they also contain numbers in some cases.

Just pushed `1.17.8` live on GitHub and in verification for the store to correct that.

I'm sorry!

**Comment by jfidelack** [comment]
I bought you a couple cups of coffee. I've been using Stadia enhanced for
years and it's wonderful. I also love seeing you engage with the community
on Reddit. Keep up the good work!

**Comment by hoangnghia0710** [comment]
No problem. Thank you very much for your effort. Love this extension a lot.
