### ISSUE TITLE
Favorite & Visibility icons + StadiaHunters Button missing on games without the animated header image.

### ISSUE THREAD

**Issue by ELowry** [ChristopherKlay/StadiaEnhanced#194]
When opening a game's "pop-up" from the [library](https://stadia.google.com/library), games further down in the list do not display the "animated header" image (the one with layered transparent images). I imagine this is done for performance.

In those games, the two icons in the top-left to toggle the Favorite and Visibility statuss of the game are missing:
![image](https://user-images.githubusercontent.com/7792033/142628626-15527ccf-2da5-4b28-82db-3d08a4fcb7b3.png)

It also looks like the StadiaHunters button is missing. Since those icons are added right after the StaidaHunters button in the code, I believe that might be where things break.

**Comment by ELowry** [comment]
The console seems to show something breaking:
`Uncaught TypeError: Cannot read properties of null (reading 'getAttribute') at enhanced.js:2877`

which seems to specifically to point to the `.getAttribute('data-app-id')` part of that line.
I imagine that value isn't available for games with that "simplified" display?

**Comment by ChristopherKlay** [comment]
Thanks for reporting!

The issue was that games with multiple screenshots, had the play button (which contains the ID) placed differently and when updating the code, i was targeting the parent element (which changes) not the button directly.

Will be fixed in `1.18.1` later today (:
