### ISSUE TITLE
Stadia Enhanced UI not displaying (Achievements.js uncaught error)

### ISSUE THREAD

**Issue by ELowry** [ChristopherKlay/StadiaEnhanced#199]
Hi there,

Just after claiming all pro games, I went to my Stadia library page and saw that most(all?) Stadia Enhanced UI elements were missing.

I'm getting a single error in the console:
![image](https://user-images.githubusercontent.com/7792033/144224455-c2f848f2-8655-488a-9190-8f7824aebd5c.png)

I imagine this is tied to a web site update. The only difference I can see is this section at the top of the page which I hadn't noticed before:
![image](https://user-images.githubusercontent.com/7792033/144224697-3618edb9-7e3a-490c-9d23-f37d746443d5.png)

**Comment by ChristopherKlay** [comment]
The extension not showing up likely has to do with the recent permission changes.

Mainly me forgetting to actually include the `/library` page, thus reloading the page while having the library open, simply doesn't load the extension to begin with. Gonna push a fix out quickly, that also includes the new "Free" filter type, that filters out games that have the "Free" tag, mostly unclaimed ones. Allows people to specifically show unclaimed games (:

On the error however; Despite the variable names and such, that function isn't actually from Stadia Enhanced?

- I don't use `let` anywhere currently
- There is no `upgradeEnhanced` function
