### ISSUE TITLE
Codec and resolution not selectable

### ISSUE THREAD

**Issue by opReturn0** [ChristopherKlay/StadiaEnhanced#2]
The Codec and Resolution that were available using the stand-alone user script are not available in the extension.
I made sure the user script and violentmonkey were uninstalled before I installed the extension.

**Comment by ChristopherKlay** [comment]
They got moved with `v1.1.0` and can be found in the settings menu (click your avatar at the top right) now, to save UI space, due to them usually not being changed all that much.

I will update the screenshots on the store soon. (:

**Comment by opReturn0** [comment]
I have found the settings thank you.

Some feedback: It is not clear what default means. 
Also, I have to select the menu about 6 times to get the desired combination of codec and resolution.
The way you previously had it was a lot more intuitive!

Thanks for your work :)

**Comment by ChristopherKlay** [comment]
Don't worry, i'm already working on a fix so Stadia doesn't close the menu every time you change the settings.
I also just pushed a new update here and in verification for the store, that fixed some issues related to the default option right now.

"Default" will use whatever codec/resolution Stadia selects during start-up. Effectively the same, compared to not having any extension installed. If that defaults to H264 or VP9 for example, depends on the device and Googles preset.
