### ISSUE TITLE
update profile image

### ISSUE THREAD

**Issue by Lordubuntu94** [ChristopherKlay/StadiaEnhanced#20]
After the recent google's updates to profiles UI, if you go to "show your profile" you can see the old pic instead of the one loaded.

Example: 
https://external-preview.redd.it/Hcqs4oXyhJiF3YaPHA7beAQuuFVqzLqAc6S3YAG1K9k.png?auto=webp&s=7b1015e874c84b345feeaab24f585b1f2047c334

**Comment by ChristopherKlay** [comment]
A hotfix is coming that will fix some of the changes made by Google as soon as i get access to the profiles function.
Right now for some reason the usual 24-36h rollout didn't reach me yet - i'll check if i can get a friends account to speed that up (:

**Comment by ChristopherKlay** [comment]
Update just went live for GitHub and into verification for the Chrome Store (:

**Comment by Lordubuntu94** [comment]
just updated to 1.5.5 thank you Christopher, nice job!

I have still one question left (regarding profile pics) :  could you add the custom image also to the friends section under each friend's profile?

You can check this clicking on one of your friends profile and then scrolling down to the bottom of the page. You will see the old google pic instead of the custom one.

**Comment by ChristopherKlay** [comment]
Absolutely.

Will be pushed as `v1.5.6` tomorrow (:

**Comment by ChristopherKlay** [comment]
v1.5.6 just went live on GitHub and is in verification for the store now.

Should fix the profile picture not showing in profile lists, as well as the new issues with styles due to changes on Stadias end.

**Comment by Lordubuntu94** [comment]
I've found another spot : https://imgur.com/TFMnkRJ

This should be the last, sorry to bother so much Christopher! xD

btw great job as always for v1.5.6

**Comment by ChristopherKlay** [comment]
Nice find.

I will wait till messaging finally hits Germany, to make sure i'm not missing anything there, then publish another hotfix.

Thanks for reporting those (:
