### ISSUE TITLE
Stream Monitor not opening in new window

### ISSUE THREAD

**Issue by SHANYUAN** [ChristopherKlay/StadiaEnhanced#205]
**Setup:**
Stadia Enhanced 1.18.6
Microsoft Edge 96.0.1054.41

**Problem:**
Double click on In-Game-Menu Icon "Stream Monitor" does open new window, but no content is shown. An error is thrown in the console: "Uncaught ReferenceError: enhanced_monitorStyle is not defined". This is the part of the code where the error is thrown:

```
    // Copy styles
    var el = document.createElement('style')
    enhanced_popMonitor.document.head.appendChild(el)
    el.innerHTML = enhanced_monitorStyle + '#enhanced_streamMonitor { display: block !important; }'

```

**Possible Solution:**
Seems like the variable name should be "enhanced_streamMonitorStyle", because this is the variable that contains other styles for element-id "#enhanced_streamMonitor"

![Screenshot 2021-12-03 163537](https://user-images.githubusercontent.com/7899872/144630241-fbb30f9b-7971-4141-92b1-585bc8aada46.png)

**Comment by ChristopherKlay** [comment]
Fix merged (:
