### ISSUE TITLE
Stadia Enhanced dosent work properly

### ISSUE THREAD

**Issue by HiImSOulja** [ChristopherKlay/StadiaEnhanced#216]
I cant acces interface or stream menu, community features, i can only acces quick acces and stadia enhaced

**Comment by ChristopherKlay** [comment]
Do you get any errors in the console (Ctrl+Shift+I > console)?

**Comment by HiImSOulja** [comment]
Uncaught TypeError: Cannot read properties of undefined (reading 'game')

**Comment by ChristopherKlay** [comment]
What language are you using?

**Comment by HiImSOulja** [comment]
Romanian language. should i change for english ?

**Comment by ChristopherKlay** [comment]
See #217 for more details and a upcoming solution (:
