### ISSUE TITLE
Visual Layer overlap

### ISSUE THREAD

**Issue by XSBIGWILLISX** [ChristopherKlay/StadiaEnhanced#218]
Hi,

A bunch of times I've logged into stadia with stadia enhanced and it gives me a small square box display in the top left hand corner of my screen and then over layers a repeat imagine of its self three times. it only fixes it self after I close stadia down and restart it but it seems to happen after I switch my laptop back on. Every time without fail I've just removed stadia enhanced and put it back on thinking that my laptop might of corrupted the file some how, I'm just gonna try that and see if it worked. but i thought you might wanna know just in case some one else is experiencing this.

Do love the extension it made me start paying for stadia pro again, Great work!!

**Comment by ChristopherKlay** [comment]
Could you try and get a screenshot of it, the next time it happens?

It's likely the streaming monitor showing up, without any content being loaded, but i can't currently replicate the issue.

Will look into it (:

**Comment by XSBIGWILLISX** [comment]
Luckily, it happen just now. I have duel screen so don't mind the second shot on the right.

but this error is consistent.

It doesn't inhibit my ability of playing but as you can see it'd make it more difficult.


![Screenshot (1)](https://user-images.githubusercontent.com/98302185/150920630-785492bf-a6fb-4253-b8d4-4fc98b696f9c.png)
.

**Comment by ChristopherKlay** [comment]
**A little update:**

Someone over on [Reddit](https://www.reddit.com/r/Stadia/comments/svdkhv/im_getting_this_glitch_while_playing_rdr2_with/) has the same issue and it's apparently the games fault, not a issue with Stadia Enhanced.

Changing between performance and visuals mode should fix it (:
