### ISSUE TITLE
StadiaEnhanced + chromecast ultra or chromecast google tv

### ISSUE THREAD

**Issue by pherm** [ChristopherKlay/StadiaEnhanced#223]
Hi @ChristopherKlay, nice job here!

is there any way to use this extension in the google tv chromecast in dev mode or similar?

**Comment by ChristopherKlay** [comment]
So far, i believe there isn't.

It's possible to use it via Kiwi Browser (or other Chrome based ones, supporting extensions) on Android devices and any Chrome based (Opera, Vivaldi, Brave, ..) Desktop Browser only.
