### ISSUE TITLE
Game Count goes to 0 with list view

### ISSUE THREAD

**Issue by TigerTJJ** [ChristopherKlay/StadiaEnhanced#225]
Title is pretty self-explanatory. When switching from grid view to list view, the count of games goes to 0.

![image](https://user-images.githubusercontent.com/17763198/156267372-d6f7ecb4-2bd8-4b7d-852a-5d1b52c21916.png)

![image](https://user-images.githubusercontent.com/17763198/156267293-47236c98-ad2d-46e4-bd20-c467ebdb3335.png)

**Comment by ChristopherKlay** [comment]
Will be fixed in `1.20.0` later today.

Thanks for reporting! (:

**Comment by TigerTJJ** [comment]
This is also fixed! Thanks!
