### ISSUE TITLE
[Bug] Stream monitor is stuck on game detection

### ISSUE THREAD

**Issue by Lordubuntu94** [ChristopherKlay/StadiaEnhanced#24]
Probably google has changed something in the code, from today it doesn't work anymore.

**Comment by ChristopherKlay** [comment]
Looking into it (:

**Comment by ChristopherKlay** [comment]
Issue will be solved with v1.6.0 and i also changed the way the stream loads the data slightly, so it should adjust on it's own if Stadia changes the WebRTC stream next time around.

Thanks for letting me know (:

**Comment by Sincide** [comment]
Having the same issue on manjaro linux (i3wm), looking forward to 1.6
