### ISSUE TITLE
Can't open Stadia enchanced options on Chrome canary.Can you fix this please

### ISSUE THREAD

**Issue by ote203** [ChristopherKlay/StadiaEnhanced#241]
When I am on Stadia home page and I click three lines (Stadia enchanced options) nothing happens,so I can't access the options and change codec and resolution.Can you fix this please?

**Comment by ChristopherKlay** [comment]
Fix is already in verification, see #240 (:

**Comment by ote203** [comment]
> Fix is already in verification, see #240 (:

Thank you so much :).Also do you know if there is any way to force a Hardware H264? My gpu is capable of doing it but for some reason every browser I try, it uses Software H264,and with that I can only use Stadia on 720p because 1080p has massive input delay probably because of software decoding. I tried to enable it in chrome settings,I tried to force it in chrome://flags but nothing seems to work.I have this problem even in Geforce NOW pc app,720p works fine but 1080 has input delay,so I guess that is also because of using Software H264 and not Hardware H264.Could it be a GPU driver problem or something like that that causes only software decoding to be used?
