### ISSUE TITLE
FPS Counter only shows 60 fps

### ISSUE THREAD

**Issue by OSRAtze** [ChristopherKlay/StadiaEnhanced#27]
When i play, for example, AC:O or Tomb Raider in High Resolution Mode, i can see that there are only 30 fps but the Stream Monitor always shows 60 fps. 

It doesn't depend on the OS. 
I testet it with Windows 10 and MacOS Big Sur.

**Comment by ChristopherKlay** [comment]
The stream monitor isn't showing what resolution/fps the actual game runs at, but the resolution/framerate the games stream is running on your end. The actual resolution of the game itself and the fps it's running at is out of my reach, sadly.

The monitor is mainly used to check if the correct codec is used, if framedrops happen with a specific codec or a certain connection and to see if the set resolution is applied.

**Comment by OSRAtze** [comment]
Thanks for your reply. 

Genieße deinen Kaffee ;-)
