### ISSUE TITLE
[Minor bug] Profile image change

### ISSUE THREAD

**Issue by Lordubuntu94** [ChristopherKlay/StadiaEnhanced#3]
When you change your profile pic with a custom one (url), if you go on one of your friends achievement page you'll see your image instead of theirs.

screen : https://imgur.com/a/IwZopHy

**Comment by ChristopherKlay** [comment]
Thanks for highlighting the issue!

A fix will be included in `v1.3.0` which should go inter verification later today, also including some new features.
