### ISSUE TITLE
Feature Request: 1440p

### ISSUE THREAD

**Issue by mlostekk** [ChristopherKlay/StadiaEnhanced#32]
Title should describe it ...

**Comment by ChristopherKlay** [comment]
1440p (2560x1440px) is actually already available, via the "2K" option under stream settings. 😋 

Stadia sadly only provides 720ß, 1080p, 1440p and 2160p streams. With 1440p afaik being a downsampled 4K stream.

**Comment by mlostekk** [comment]
Ah okay, Somehow i thought 2k was 1080p. I can just get the 1440p to run if i leave it as "native"

**Comment by ChristopherKlay** [comment]
Yea, "Native" starts games in the resolution Stadia itself detects, based on your screen size.

Selecting 2K/4K (1440p/2160p) simply sets your screen size to the needed resolution so Stadia detects them as supported.

**Comment by mlostekk** [comment]
Okay great. Thanks
