### ISSUE TITLE
Force HDR support

### ISSUE THREAD

**Issue by filippogasbarro** [ChristopherKlay/StadiaEnhanced#33]
Please make it possible to force HDR support, and HDR information would be nice

**Comment by ChristopherKlay** [comment]
Currently not possible, because it's not actually enabled on Stadias side, afaik.

They even removed the HDR support part that stated it works on a PC from the support document, limiting it to chromecasts for now.

**Comment by Primajin** [comment]
Is this still limited to Chromecast only? In case they reenabled this for PC I'd be really interested in forcing HDR as well.
I have a HDR capable monitor but it only goes into HDR mode if it detects an HDR source - while I fear Stadia will not stream HDR when the monitor is not in HDR mode - so I'm in a deadlock there 🔃

**Comment by ChristopherKlay** [comment]
According to Google's own [support page](https://support.google.com/stadia/answer/9607891#zippy=%2Crequirements-for-hdr), HDR is sadly srtill limited to TV (Chromecast).
