### ISSUE TITLE
Extension menus not working correctly

### ISSUE THREAD

**Issue by RasterCrow** [ChristopherKlay/StadiaEnhanced#34]
I don't know when it happened but I can't seem to find the options dropdown menu anymore? [Image example](https://i.imgur.com/weuX0L5.png).
Not even the search functionality.
And also the in game menu is now misaligned and kinda broken. [Example](https://i.imgur.com/ry8w4H2.png).
I don't know if maybe Google updated something and broke the extension or if the problem is on my side; everything worked great some days ago.
I tried reinstalling but it's still the same.

**Comment by ChristopherKlay** [comment]
Stadia is currently making some bigger changes that roll out stil, including changes to the homescreen and other things.

The extension won't work correctly, until i get the new version - a fix will be deployed directly after.

**Comment by RasterCrow** [comment]
No problem, thank you for the work your doing!

**Comment by Anvnamnet** [comment]
> Stadia is currently making some bigger changes that roll out stil, including changes to the homescreen and other things.


Where can I read about the changes they are doing etc?

**Comment by ChristopherKlay** [comment]
You can't really, unless changes are being released for some people.
In this case some people got the new changes early and showed them [here](https://www.youtube.com/watch?v=pTCCEA4n-tI).

There isn't a "these changes are coming soon" like source, sadly.

**Comment by Anvnamnet** [comment]
> You can't really, unless changes are being released for some people.
> In this case some people got the new changes early and showed them [here](https://www.youtube.com/watch?v=pTCCEA4n-tI).
> 
> There isn't a "these changes are coming soon" like source, sadly.

Ok. Thank you.. I you can fix it soon. Love the extension! I miss being able to change resolution =)
Good luck in the future!

**Comment by Tordp** [comment]
Chrome version 87.0.4280.88 (Officiell version) (64 bit)
Stadia Enhanced version 1.7.0
Locale Swedish/Sweden

![stadia_enhanced_screen](https://user-images.githubusercontent.com/28449484/101497810-a821bf80-396b-11eb-8d16-27fc000d683b.PNG)

I still don't have the pulldown menu in my Stadia. Running latest version of everything. It worked until a few days ago just before 1.7.0 was released.

**Comment by Anvnamnet** [comment]
> I still don't have the pulldown menu in my Stadia. Running latest version of everything. It worked until a few days ago just before 1.7.0 was released.
- @Tordp 

Let's hope it gets a fix before Cyberpunk release! =)

**Comment by ChristopherKlay** [comment]
v1.7.0 actually fixes the menu not showing up correctly already.

There was a minor error that stopped the extension from loading at all when using it in swedish however.

I'll push v1.7.1 including a fix for this and some other details in a moment (:

**Comment by Tordp** [comment]
> There was a minor error that stopped the extension from loading at all when using it in swedish however.
> 
> I'll push v1.7.1 including a fix for this and some other details in a moment (:

Version 1.7.1 is now installed and the pulldown menu is back.

Thanks Christopher!

**Comment by archon810** [comment]
I have 1.7.1 up, which brings back the menus (thanks!) but the grid isn't working - it's still 2 games wide.

**Comment by ChristopherKlay** [comment]
Theres a couple of things like the grid, game filter and shortcuts, that i won't be able to fix until i actually get the new design changes.
They roll out on a per-account basis with some people getting those changes a week ago, while others don't have any of them yet (like myself) sadly. As soon as those changes are live, those issues will be fixed.

**Comment by archon810** [comment]
Would it help if I sent you a saved html page?

**Comment by ChristopherKlay** [comment]
It would allow me to prepare fixes - but it would also be a lot more work since i can't live preview changes.

I also can't just release a fix knowing that a huge amount of people is still on the old version, because the new version would stop working for the old design. Since i'm pretty much the last person to get the changes somehow, by the time i get them, i will most likely be able to just release a patch the same day.

**Comment by ChristopherKlay** [comment]
I just opened a new topic over under discussions #40 for this topic.
