### ISSUE TITLE
Cannot find Stream Monitor overlay

### ISSUE THREAD

**Issue by ramonarroyo** [ChristopherKlay/StadiaEnhanced#36]
I must have moved the stream monitor off screen and now I cannot get it back. No matter how many times I click on the option, it doesn't reset its position. I have two monitor setup and they are different resolutions (4K & 1440p) so perhaps that might have had something to do with it when moving Chrome around. Tried uninstalling and reinstalling, no luck.

**Comment by ChristopherKlay** [comment]
I definitely should've thought about this and will fix it with the monitor checking if it's on-screen in the next update.

In the meantime, you can easily fix this however, by accessing the settings manually.

1. Visit the Stadia homepage
2. Hit Ctrl+Shift+I
3. Go to "Application" at the top
4. Open up "Local Storage" on the left and click the "stadia.google.com" option

This brings up the place where Stadia Enhanced is saving it's settings. Deleting the value for `enhanced_monitorPosition` will reset the position of the monitor.

**Comment by idealleee** [comment]
Hi, I cannot find it either. I am using an external monitor with the Macbook Pro lid closed.

**Comment by ramonarroyo** [comment]
> Hi, I cannot find it either. I am using an external monitor with the Macbook Pro lid closed.

Follow the 4 steps from Christopher above and then right click on stadia.google.com and click Clear. That worked for me. Deleting the value for `enhanced_monitorPosition` did not, it would show up half a second later with the same values. It would also prevent me from overrwriting the values.

**Comment by ChristopherKlay** [comment]
You can also disable the extension, reload Stadia and then change any settings without them being set back - i should've mentioned that.

I just pushed v1.7.2 into verification and updated the project on GitHub to (hopefully) include a fix for this. Not only will the monitor be unable to get moved outside the available screen area this time, you can also just reset it's position by double-clicking the "Streaming Monitor" menu item at any point.

**Comment by fredrikaverpil** [comment]
I can't even figure out which setting enables the overlay... what should I enable?

![image](https://user-images.githubusercontent.com/994357/102689021-5561c680-41fb-11eb-8e25-6f6a1be87102.png)
