### ISSUE TITLE
Can't force 4k with Stadia enhanced

### ISSUE THREAD

**Issue by xlivin** [ChristopherKlay/StadiaEnhanced#37]
When I start a game and set the game in 4k I get this error, if I click (re-open) the game returns to give the same error
CPU: i3 8350k
GPU: 970
![image](https://user-images.githubusercontent.com/20870629/101823384-f3ce9780-3b2a-11eb-9856-1503c5424de7.png)

**Comment by xlivin** [comment]
I think at this point my HW is not supporting it, am I right? My monitor is Full hd

**Comment by ChristopherKlay** [comment]
You can check if your GPU supports VP9 decoding @ 4K by opening `chrome://gpu/` and looking at the video acceleration info.

If your GPU doesn't support VP9 decoding for 3840x2560, you will most likely run into issues, yes.

**Comment by walkafwalka** [comment]
Same here. I had to switch to fallback to Stadia+.

**Comment by ChristopherKlay** [comment]
I just booted up "Into the Breach" and while the game loads in 720p for some reason, it switches to 4K at the start screen just fine. I do still have the "old" version (like most people apparently?) without the updated homescreen and other changes however.

Are you two on the new version with the changes applied (i.e. the last played game now is a bigger tile on the homescreen and not a fullpage background anymore and such), or on the "old" version?

**Comment by xlivin** [comment]
I DID IT! Edge + Stadia enhanced. (Only edge, chrome didn't work)

![image](https://user-images.githubusercontent.com/20870629/101886493-db4a9580-3b9b-11eb-84e9-8ee5d6dd58a4.png)

**Comment by walkafwalka** [comment]
I do have the new UI. As @xlivin suggested, using Edge works flawlessly.

**Comment by CobraBytez** [comment]
Was working fine on Edge for me the past couple days, no longer works tonight. Getting the same "reopen game".

**Comment by xlivin** [comment]
It happens when the servers are too full, try again in the morning or
afternoon

Il giorno sab 12 dic 2020 alle ore 05:20 CobraBytez <
notifications@github.com> ha scritto:

**Comment by ChristopherKlay** [comment]
Are you still having issues on the newest version?

Outside of some factors i can't change (i.e. Google having some issues with 4K in games like Cyberpunk) everything should work fine by now.

**Comment by CobraBytez** [comment]
Hi Christopher,

Thanks for getting back to me. I can still only do 4K when connected to
VPN. I've discovered this week that if I disconnect from the VPN, the game
kicks me (as expected as I change IPs), but when I reconnect without the
VPN immediately it's 4K again, until I have to exit then I have to repeat
that sequence.

I have a piHole and thought it was something to do with DNS, but even after
completely disabling that and going through 8.8.8.8 the issue persists.

But yes, in answer to your question, same issue with 1.04.

Thanks again,

Matt

**Comment by ChristopherKlay** [comment]
Seeing that the extension doesn't actually manipulate your network connection itself and only changes the screen information and some minor UI elements (things unaffected by a VPN), i'm afraid this is most likely not an issue with the extension itself.

The output of `localStorage.setItem("video_codec_implementation_by_codec_key");` (Ctrl+Shift+I to open the console) without the VPN compared to after dropping the VPN but still streaming in 4K might be interesting in this case.

**Comment by CobraBytez** [comment]
Looks like the images I sent might be too large, if so please let me know
and I'll host them on Imgur. (If you didn't see my reply, got a failed to
deliver due to size from your GitHub address).

**Comment by CobraBytez** [comment]
(Just in case the images didn't come through on my first email, here's
Imgur links)... Thanks for getting back to me, here's the results and some
extra info:

Before VPN (1920x1080 in game):
http://imgur.com/AVOfyPV

 After VPN:
http://imgur.com/rbH0x3y

Also included after VPN output from Stadia Enhanced plugin to demonstrate
4K does work under VPN:
http://imgur.com/vrOhoX0

And my Windows Graphics settings:
http://imgur.com/QshDO9a

In case it comes up, the issue persists if I set Windows resolution to
3840x2160.

Thanks again,

Matt

**Comment by ChristopherKlay** [comment]
Yea, this sadly confirms what i thought in the first place; This most likely isn't the extension running into issues.

In both situations (VPN and no-VPN) the codec is correctly and Stadia isn't reverting/overwriting the detection, which means the start-up check didn't run into issues. I first thought `video_codec_implementation_by_codec_key_using_local_check` affects it, but not only is that defaulting to VP9 (h264 would've locked you into 1080p here) as well, it also doesn't change when 4K isn't available (i.e. the VPN is off).

I'm curious; Does this happen with all games and other devices on the same network?

**Comment by ChristopherKlay** [comment]
Update: Someone just made a [post over on reddit](https://www.reddit.com/r/Stadia/comments/kf7xwh/howto_force_4k_streaming_on_cyberpunk_2077/).

I've checked previous issues related to this and it looks like this indeed isn't an issue based on Stadia Enhanced, but Stadia (more specifically mostly Cyberpunk) itself.

**Comment by CobraBytez** [comment]
Thanks for the update Christopher, that post describes my current process
exactly, although weirdly I don't need to go so far as to use an American
IP, it works from a Toronto based VPN just fine.

Is there any indication what's causing it? I'm in IT as well and I'm
genuinely curious. Is there any intent to track down the problem and solve
it?

**Comment by ChristopherKlay** [comment]
According to Googles support, the issue is "unrelated to our server capacity" and has something to do with CDPR/Cyberpunk specifically. While that sounds kinda weird, it makes sense, seeing that other titles at 4K would need similar levels of performance but work fine.

In terms of what could possibly affect this, or create the issue, in terms of differences that are affected by a VPN however.. i honestly got absolutely no idea.

**Comment by CobraBytez** [comment]
Sounds good, thanks very much again for all the help and information, and
all your hard work!

**Comment by ChristopherKlay** [comment]
Thank you for using the extension and giving feedback!
I will keep this open for now, labeled as a stadia bug and keep you updated on the issue when possible.

**Comment by ChristopherKlay** [comment]
Update on the situation from [9to5](https://9to5google.com/2020/12/17/cyberpunk-2077-stadia-4k-1080p-issue/).

> During times of extraordinarily high usage, you may experience a brief dip in connectivity, causing your gameplay session to end. This is temporary, isolated to a single title and caused by an exceptionally high volume of gamers connecting to your local data center, which may subsequently route your gameplay to a location further away. When this happens, your connection time might increase beyond our threshold. With this being said, I kindly ask that you try connecting again in a few minutes as the situation should self-resolve as sessions open up.
