### ISSUE TITLE
Forcing 1440p keeps going to 4K on Mac

### ISSUE THREAD

**Issue by marekpw** [ChristopherKlay/StadiaEnhanced#41]
I use MacOS Catalina 10.15.7 on a 2017 Macbook Pro. I run Stadia on Chrome 87.0.4280.88.

When I try to force 1440p stream with Stadia Enhanced, the games (Destiny 2 and Cyberpunk 2077) still occasionally jump to 4K. This immediately increases the input lag to the point the game isn't playable before it goes back down to 1440p.

Is there any way to fix this? I assume Stadia Enhanced just lets Stadia know that my setup supports 1440p. Why does Stadia then still try to serve me a 4K stream when my monitor does not even support that resolution?

I love Stadia Enhanced by the way. Thanks for any help

**Comment by ChristopherKlay** [comment]
That definitely shouldn't happen. I tested 2K/4K earlier with "Into the Breach" and "Destiny 2" and had no such issue.

Curious, if you select 1440p and then open the console (Ctrl+Shift+I) and copy&paste this into it;

`screen.availWidth + "x" + screen.availHeight`

Is it showing up as 1440p / 2560x1440?

**Comment by marekpw** [comment]
Yeah, that shows as 2560x1440. I found a couple of people on Reddit reporting the same thing. It seems to be MacOS owners only.

**Comment by marekpw** [comment]
Here's a quick showcase of the variable resolution with forced 1440p: https://youtu.be/-aZkOOMZCgQ

**Comment by ChristopherKlay** [comment]
That's definitely weird.

Google actually checks both your chrome screen info and available screen size (which is what Stadia Enhanced effectively fakes) and only allows 4K streams if the screen area fits the content you are streaming to. In this case however either MacOS overwrites your available screen size to 4K (which wouldn't make sense?) or Stadia simply decides to stream a 2160p source to a 1440p screen.. which also shouldn't happen.

I'll keep an eye open when i'm pushing the next hotfix (as soon as the new design is available for most people) and will see if the same thing happens. Sadly no access to a MacOS based device to test it :/

**Comment by marekpw** [comment]
What’s interesting is if I set the resolution to native, just with VP9 enforced, I get a constant 1440p.




---- V Ne, 13 Pro 2020 18:45:39 +0100 Christopher Klay <notifications@github.com> napsal/a ----




That's definitely weird.

Google actually checks both your chrome screen info and available screen size (which is what Stadia Enhanced effectively fakes) and only allows 4K streams if the screen area fits the content you are streaming to. In this case however either MacOS overwrites your available screen size to 4K (which wouldn't make sense?) or Stadia simply decides to stream a 2160p source to a 1440p screen.. which also shouldn't happen.

I'll keep an eye open when i'm pushing the next hotfix (as soon as the new design is available for most people) and will see if the same thing happens. Sadly no access to a MacOS based device to test it :/

**Comment by ChristopherKlay** [comment]
Could you do the following;

1. Set the extension to VP)/Native
2. Start a game and wait for it to fully load
3. Copy `localStorage.getItem("video_codec_implementation_by_codec_key");` into the console (Ctrl+Shift+I)
4. Post the result here

This honestly sounds like either the extension can't set the codec for some reason, or the codec that's set isn't what Stadia actually requires/uses on Macs - which would indeed be weird.

**Comment by Drjacky** [comment]
<img width="457" alt="Screen Shot 2020-12-19 at 10 33 44" src="https://user-images.githubusercontent.com/2296754/102687259-ae266480-41e5-11eb-8db0-f94542e1d5c4.png">
Although, when I'm in the game, Ctrl + Shift + L doesn't bring the console so, I opened it as a separated window, then I ran those commands.
But still, the result is:  

https://imgur.com/tQbYDw1


https://www.reddit.com/r/Stadia/comments/kd223s/blurry_cyberpunk_2077_on_stadia/ggaafac/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by ChristopherKlay** [comment]
> Although, I do not have a Pro account. Should I set to 4K or Native?

Both will deliver the same quality, because 4K isn't available without Pro.
The extension only allows you to select the resolution, if for example you want to play in 4K on a 1080p screen - it can't force 4K if you are not actually on Pro.

**Comment by wsrast** [comment]
First of all, thanks a ton to @ChristopherKlay for this extension. Great work!

I'm also seeing odd behavior on a ultrawide screen, but on Windows 10 Chrome. The available res is `3440x1440`, but the toggles in the UI are showing only settings for `2560x1440` and `3840x2160`, neither of which appears to produce the right aspect ratio. I get black bars on left and right either way. I've tried the `Native` setting as well, and all of these set to VP9 codec.
`"{"vp9":"ExternalDecoder"}"`

**Comment by ChristopherKlay** [comment]
That's sadly because Stadia doesn't support ultrawide monitors in the first place. The stream is always 16:9 at the given selectable resolutions, out of which both 1440p and 2160p require VP9 as the selected codec.

There currently isn't any way to remove black bars on non-16:9 displays, without heavily deforming/stretching the stream output.
