### ISSUE TITLE
new ui cant change number of games per row

### ISSUE THREAD

**Issue by derekagraham78** [ChristopherKlay/StadiaEnhanced#43]
if you change to 6 it still shows 2 only.

**Comment by ChristopherKlay** [comment]
Did you run version `1.7.4` when testing this, or still `1.7.3`?

`1.7.4` works perfectly fine for me on the new UI.

**Comment by derekagraham78** [comment]
i dont remember the version number but works now but in a weird way, setting to 6 shows 9 games

**Comment by ChristopherKlay** [comment]
There's currently a bug when getting the game identifiers (used for shortcuts and filtering).

If you open Stadia normally via the [homepage](https://stadia.google.com/home) everything should work, but it stops working if you load the page via a shop URL or the similar (like the "Pro" and "Captures" shortcut).

Currently working on a fix.
