### ISSUE TITLE
extension fails to load with `cannot read property 'split' of null`

### ISSUE THREAD

**Issue by fiws** [ChristopherKlay/StadiaEnhanced#44]
![image](https://user-images.githubusercontent.com/3409958/102711347-3e81a980-42b9-11eb-86e5-f8a1e88185f7.png)

Don't know how this ever worked.. Maybe this changed in the latest update?

**Comment by ChristopherKlay** [comment]
Thank you for reporting this issue!

Someone else on Reddit had the same issue [here](https://www.reddit.com/r/Stadia/comments/kgrri8/bringing_up_the_option_to_toggle_vp9_and_2k_res/) and i already prepared a hotfix that's going live on GitHub now and should be available and automatically updated on the chrome store real soon (:

**Comment by fiws** [comment]
No worries.
This is already fixed right? I think we can close this then.
