### ISSUE TITLE
iMac 2015 (27", 5k) awful lags on 4k and 2k

### ISSUE THREAD

**Issue by Grakaj** [ChristopherKlay/StadiaEnhanced#50]
This add-on is a curse! It showed me what 4k games can look like and my jaw dropped. Unfortunately, when I try to playing in these resolutions I have a terrible lag - both when playing on the Xbox One pad and with the keyboard and mouse.

Is there any resolution or do I have to go back to Full HD with a broken heart?

**Comment by ChristopherKlay** [comment]
My knowledge about Macs in general is sadly pretty limited.

Afaik without Big Sur and a 2017 or later model, VP9 hardware support won't be there, which means you won't be able to play in 4K due to software decoding not being processed fast enough by the CPU alone.

**Comment by Grakaj** [comment]
Sadly for me, you must be wright. Today we found out that on my friend's iMac (the new one from 2020) with your add-on, 4k works great on Stadia even without official support, so thanks to your work he is very, very happy 😊 Thanks for it! 🍻
