### ISSUE TITLE
Stream Monitor - Compression rendering "NaN"

### ISSUE THREAD

**Issue by ds8k** [ChristopherKlay/StadiaEnhanced#54]
The stream monitor component looks like it's incorrectly running a `toFixed` on a non-number, resulting in "NaN" getting rendered:

![Screen Shot 2020-12-27 at 12 57 18 PM](https://user-images.githubusercontent.com/4458812/103176831-14912f80-4843-11eb-91ee-dc4de2455061.png)

**Comment by ChristopherKlay** [comment]
Curious, does this happen all the time, or rarely/once?

I just tested it a couple of times and while it shows `NaN` during the initial loading (same for latency) it shows the correct value after ~5-10sec and never reverts back to `NaN` for me.

**Comment by ds8k** [comment]
As the screenshot shots, I was 11 minutes into my session and not once did it show anything other than NaN.

**Comment by ChristopherKlay** [comment]
This should be solved with the recent patch.
