### ISSUE TITLE
Option to disable the forced resolution by default

### ISSUE THREAD

**Issue by Problematist** [ChristopherKlay/StadiaEnhanced#6]
I have to use 720p because my CPU is too old and I'd imagine others have an internet connection that isn't good enough for their native resolution.

**Comment by ChristopherKlay** [comment]
There is no resolution forced by default in the first place, in fact, the entire expansion isn't forcing a resolution.

If you select 2K/4K, all the extension does is changing the width/height values of your chrome window to those resolutions, which makes Stadia think your screen is the said resolution, thus allowing you to stream in 2K/4K if you chose said option. It defaults to 1080p (there was actually an error there as well with width setting the height, i just fixed that) but nothing forces the stream to be 1080p, if you limit it to 720p in the settings.

I just tested it and limiting Stadia to 720p on a 1080p starts the game in 720p as expected.
