### ISSUE TITLE
Latest version drop-down menu doesn't work on Chromium 86

### ISSUE THREAD

**Issue by michaelbutler** [ChristopherKlay/StadiaEnhanced#62]
![Screenshot_20210102_135903](https://user-images.githubusercontent.com/521702/103464585-f7f16d80-4d02-11eb-9aa1-8d3e35569c82.png)

I'm on Chromium 86, Manjaro Linux (kind of a convoluted set up honestly, did this so I could get VP9 hardware accelerated decoding working with Stadia). The latest update has a vertical drop-down menu which is not scrollable as shown in the screen shot. My screen size is 3440x1440.

The top of the menu is somewhere off-screen, using the mousewheel doesn't scroll it up or down, it just kind of stays like this. Is there an easy way for me to downgrade to the previous version? I don't know what else to try.

**Comment by michaelbutler** [comment]
Just an update here, I removed the store version of the extension, [git cloned](https://dev.to/ben/how-to-install-chrome-extensions-manually-from-github-1612) an earlier sha1 (39bc8112b7ad14207a3d26f89dd688ec716e1fbc) from when it was still horizontal, and the menu is all visible now. So this works as a workaround but not sure how many this issue affects on the latest version.

**Comment by ChristopherKlay** [comment]
If you run the newest version and throw this here into the console;
```
var menu = document.getElementById("enhanced_SettingsDropContent")
console.log(menu.style.position + " - " + menu.style.top + ";" + menu.style.left + ";" + menu.style.right + ";" + menu.style.bottom)
```
Is the output actually matching this?
``fixed - 4rem;auto;1.5rem;1.5rem``

It's most likely an issue with support about CSS `inset` that i could fix easily, if that's not the case.

**Comment by michaelbutler** [comment]
weird, I have no idea what happened but it is working now. after this issue I uninstalled it, then I installed `Stadia+`. Now I uninstalled `Stadia+`, installed this one again, and the scroll bar works fine there. Thanks!

For completeness, I do get this when running that command in the console.

`fixed - 4rem;auto;1.5rem;1.5rem`

**Comment by michaelbutler** [comment]
Oh, actually I just realized that after I opened this issue, I also updated to Chromium 87 so I don't know what actually fixed it.

**Comment by ChristopherKlay** [comment]
It was most likely the update to v87, since `inset` afaik wasn't previously supported without enabling a flag.
Since the difference is tiny, i just replaced it with the individual top/bottom/left/right values to support earlier versions as well in the patch for `1.8.2` that will go live later.

Thanks for making me aware of that issue (:
