### ISSUE TITLE
Please include Stripe payment in your buymeacoffee-profile

### ISSUE THREAD

**Issue by peraltaninenine** [ChristopherKlay/StadiaEnhanced#63]
Thanks. :)

**Comment by ChristopherKlay** [comment]
I had it enabled in the past, but seeing that there isn't any company involved, Stripe would basically force me to publish my own private phone number (or a new one i would have to keep just for the service) on the invoice, which is something i'd like to avoid.

After all the buymeacoffee page is more a "thank you" and not for example a required payment to a company.

**Comment by peraltaninenine** [comment]
Thanks for the fast reply. Just wanted to give back a favor because I love Stadia Enhanced but I boycott PayPal.. that's all ;) 
If you'll ever have other options I'll be glad to support you :) (Or I'm just going to ask a friend to PayPal)

**Comment by ChristopherKlay** [comment]
I never tried it, but afaik PayPal also allows you to make payments without registering in some cases - i can't confirm if that works in this case however.

I do appreciate the thought however and hope you have a great weekend (:
