### ISSUE TITLE
Decoding goes wrong on Huawei

### ISSUE THREAD

**Issue by awwe** [ChristopherKlay/StadiaEnhanced#79]
I encountered a problem. 

I think it is because of this:

On Huawei the hardware support for decoding is in this package:

OMX.hisi.decoder.avc

But when I try running with h264 the game does not start. 

c2.android.avc.decoder has no hardware support if i look into my Huawei (kirin 710)

Is there a possibility to make a fallback to this package?

**Comment by awwe** [comment]
Here is some more related to this and an solution 

https://github.com/twilio/twilio-video.js/issues/467

**Comment by awwe** [comment]
Is Stadia using webRTC?

https://github.com/twilio/video-quickstart-android/issues/500

There is an upgrade that solve this

**Comment by ChristopherKlay** [comment]
I'll be looking into it once i'm done with the next patch, but please post this again as a discussion under ideas & requests - this isn't an issue with the extension.
