### ISSUE TITLE
French Translation File

### ISSUE THREAD

**Issue by ELowry** [ChristopherKlay/StadiaEnhanced#8]
```
LANG: fr

"default":"Par Défaut",
"native":"Natif",
"disabled":"Désactivé",
"windowed":"Fenêtré",
"fullscreen":"Plein Écran",
"searchstore":"Rechercher dans le Store",
"onsale":"En promotion",
"prodeals":"Offres Stadia Pro",
"allgames":"Tous les jeux",
"usermedia":"Captures & Vidéos",
"gridsize":"Taille de la Grille",
"friendslist":"Liste d'Amis",
"igoverlay":"Overlay en-jeu",
"listoverlay":"Liste & Overlay",
"filtertoggle":"Activer/Désactiver le Filtrage",
"filterquick":"Filtrage Rapide",
"invitebase":"Copier le lien d'Invitation",
"inviteactive":"Copié&nbps;!",
"searchbtnbase":"Rechercher sur",
"avatarpopup":"URL du nouvel avatar (vide = par défaut):",
"searchheader":"Jeux avec",
"sessiontime":"Durée de la session",
"codec":"Codec",
"resolution": "Résolution",
"trafficsession":"Trafic de la session",
"trafficcurrent":"Trafic actuel",
"trafficaverage":"Trafic moyen",
"packetloss":"Paquets perdus",
"framedrop":"Images perdues",
"latency":"Latence",
"jitter":"Tampon de gigue",
"compression":"Compression",
"streammon":"Moniteur de Stream"
```

**Comment by ELowry** [comment]
Fixed some mistakes. Thanks to [u/Ledavix](https://www.reddit.com/r/Stadia/comments/iz5fbc/stadia_enhanced_the_extension_needs_you/g6nzgfg/) on Reddit!

**Comment by ChristopherKlay** [comment]
Just updated the translation file with the missing line; `"resolution": "Resolution",`
Would be lovely if you could translate that, so i can push a hotfix for the streaming monitor (:

**Comment by ELowry** [comment]
Updated =)

**Comment by ChristopherKlay** [comment]
New lines for v1.6.0 and the new settings menu/options.

    "stream": "Stream",
    "community": "Community",
    "speedtest": "Speedtest",
    "quickaccess": "Quick Access",
    "messages": "Messages",
    "prolabel": "Pro Label",
    "homegallery": "User Gallery",
    "quickprev": "Message Preview",
    "quickrep": "Quick Reply",
    "offlinefriend": "Offline Friends",
    "invisiblefriend": "Invisible Friends",
    "avatar": "Avatar"

**Comment by ELowry** [comment]
```
"stream": "Stream",
"community": "Communauté",
"speedtest": "Test de Débit",
"quickaccess": "Accès Rapide, <<<
"messages": "Messages",
"prolabel": "Vignette Pro",
"homegallery": "Galerie de l'Utilisateur",
"quickprev": "Prévisualisation du Message",
"quickrep": "Réponse Rapide",
"offlinefriend": "Amis Connectés",
"invisiblefriend": "Amis Masqués",
"avatar": "Avatar"
```

Just a few questions to make sure:

- What does the `homegallery` string correspond to?
- Are `invisiblefriend` actively hidden or just not available?

**Comment by ChristopherKlay** [comment]
`homegallery` is about the little media section at the bottom of the startpage, where you see the last 3 screenshots/clips.

`invisiblefriend` is for people who are "invisible" in terms of not sharing their online status. I.e. you can't see "Offline" or their current online status and such in the friends list.

**Comment by ELowry** [comment]
Ok, thanks, it should be good now =)

**Comment by ChristopherKlay** [comment]
Huge thanks (:

**Comment by ChristopherKlay** [comment]
v1.7.0 was slightly rushed due to changes on Googles end, thus i applied the new version and forgot two strings for 1.7.0;
```
"streammode": "Streaming Mode",
"interface": "Interface"
```
These will be added in a later hotfix when available.

**Comment by ELowry** [comment]
This is an easy one ;)
```json
"streammode": "Mode Streaming",
"interface": "Interface"
```
